package com.zlx.clinic.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class AdminExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table admin
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table admin
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table admin
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public AdminExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table admin
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andAIdIsNull() {
            addCriterion("a_id is null");
            return (Criteria) this;
        }

        public Criteria andAIdIsNotNull() {
            addCriterion("a_id is not null");
            return (Criteria) this;
        }

        public Criteria andAIdEqualTo(Integer value) {
            addCriterion("a_id =", value, "aId");
            return (Criteria) this;
        }

        public Criteria andAIdNotEqualTo(Integer value) {
            addCriterion("a_id <>", value, "aId");
            return (Criteria) this;
        }

        public Criteria andAIdGreaterThan(Integer value) {
            addCriterion("a_id >", value, "aId");
            return (Criteria) this;
        }

        public Criteria andAIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("a_id >=", value, "aId");
            return (Criteria) this;
        }

        public Criteria andAIdLessThan(Integer value) {
            addCriterion("a_id <", value, "aId");
            return (Criteria) this;
        }

        public Criteria andAIdLessThanOrEqualTo(Integer value) {
            addCriterion("a_id <=", value, "aId");
            return (Criteria) this;
        }

        public Criteria andAIdIn(List<Integer> values) {
            addCriterion("a_id in", values, "aId");
            return (Criteria) this;
        }

        public Criteria andAIdNotIn(List<Integer> values) {
            addCriterion("a_id not in", values, "aId");
            return (Criteria) this;
        }

        public Criteria andAIdBetween(Integer value1, Integer value2) {
            addCriterion("a_id between", value1, value2, "aId");
            return (Criteria) this;
        }

        public Criteria andAIdNotBetween(Integer value1, Integer value2) {
            addCriterion("a_id not between", value1, value2, "aId");
            return (Criteria) this;
        }

        public Criteria andAPasswordIsNull() {
            addCriterion("a_password is null");
            return (Criteria) this;
        }

        public Criteria andAPasswordIsNotNull() {
            addCriterion("a_password is not null");
            return (Criteria) this;
        }

        public Criteria andAPasswordEqualTo(String value) {
            addCriterion("a_password =", value, "aPassword");
            return (Criteria) this;
        }

        public Criteria andAPasswordNotEqualTo(String value) {
            addCriterion("a_password <>", value, "aPassword");
            return (Criteria) this;
        }

        public Criteria andAPasswordGreaterThan(String value) {
            addCriterion("a_password >", value, "aPassword");
            return (Criteria) this;
        }

        public Criteria andAPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("a_password >=", value, "aPassword");
            return (Criteria) this;
        }

        public Criteria andAPasswordLessThan(String value) {
            addCriterion("a_password <", value, "aPassword");
            return (Criteria) this;
        }

        public Criteria andAPasswordLessThanOrEqualTo(String value) {
            addCriterion("a_password <=", value, "aPassword");
            return (Criteria) this;
        }

        public Criteria andAPasswordLike(String value) {
            addCriterion("a_password like", value, "aPassword");
            return (Criteria) this;
        }

        public Criteria andAPasswordNotLike(String value) {
            addCriterion("a_password not like", value, "aPassword");
            return (Criteria) this;
        }

        public Criteria andAPasswordIn(List<String> values) {
            addCriterion("a_password in", values, "aPassword");
            return (Criteria) this;
        }

        public Criteria andAPasswordNotIn(List<String> values) {
            addCriterion("a_password not in", values, "aPassword");
            return (Criteria) this;
        }

        public Criteria andAPasswordBetween(String value1, String value2) {
            addCriterion("a_password between", value1, value2, "aPassword");
            return (Criteria) this;
        }

        public Criteria andAPasswordNotBetween(String value1, String value2) {
            addCriterion("a_password not between", value1, value2, "aPassword");
            return (Criteria) this;
        }

        public Criteria andANameIsNull() {
            addCriterion("a_name is null");
            return (Criteria) this;
        }

        public Criteria andANameIsNotNull() {
            addCriterion("a_name is not null");
            return (Criteria) this;
        }

        public Criteria andANameEqualTo(String value) {
            addCriterion("a_name =", value, "aName");
            return (Criteria) this;
        }

        public Criteria andANameNotEqualTo(String value) {
            addCriterion("a_name <>", value, "aName");
            return (Criteria) this;
        }

        public Criteria andANameGreaterThan(String value) {
            addCriterion("a_name >", value, "aName");
            return (Criteria) this;
        }

        public Criteria andANameGreaterThanOrEqualTo(String value) {
            addCriterion("a_name >=", value, "aName");
            return (Criteria) this;
        }

        public Criteria andANameLessThan(String value) {
            addCriterion("a_name <", value, "aName");
            return (Criteria) this;
        }

        public Criteria andANameLessThanOrEqualTo(String value) {
            addCriterion("a_name <=", value, "aName");
            return (Criteria) this;
        }

        public Criteria andANameLike(String value) {
            addCriterion("a_name like", value, "aName");
            return (Criteria) this;
        }

        public Criteria andANameNotLike(String value) {
            addCriterion("a_name not like", value, "aName");
            return (Criteria) this;
        }

        public Criteria andANameIn(List<String> values) {
            addCriterion("a_name in", values, "aName");
            return (Criteria) this;
        }

        public Criteria andANameNotIn(List<String> values) {
            addCriterion("a_name not in", values, "aName");
            return (Criteria) this;
        }

        public Criteria andANameBetween(String value1, String value2) {
            addCriterion("a_name between", value1, value2, "aName");
            return (Criteria) this;
        }

        public Criteria andANameNotBetween(String value1, String value2) {
            addCriterion("a_name not between", value1, value2, "aName");
            return (Criteria) this;
        }

        public Criteria andAGenderIsNull() {
            addCriterion("a_gender is null");
            return (Criteria) this;
        }

        public Criteria andAGenderIsNotNull() {
            addCriterion("a_gender is not null");
            return (Criteria) this;
        }

        public Criteria andAGenderEqualTo(String value) {
            addCriterion("a_gender =", value, "aGender");
            return (Criteria) this;
        }

        public Criteria andAGenderNotEqualTo(String value) {
            addCriterion("a_gender <>", value, "aGender");
            return (Criteria) this;
        }

        public Criteria andAGenderGreaterThan(String value) {
            addCriterion("a_gender >", value, "aGender");
            return (Criteria) this;
        }

        public Criteria andAGenderGreaterThanOrEqualTo(String value) {
            addCriterion("a_gender >=", value, "aGender");
            return (Criteria) this;
        }

        public Criteria andAGenderLessThan(String value) {
            addCriterion("a_gender <", value, "aGender");
            return (Criteria) this;
        }

        public Criteria andAGenderLessThanOrEqualTo(String value) {
            addCriterion("a_gender <=", value, "aGender");
            return (Criteria) this;
        }

        public Criteria andAGenderLike(String value) {
            addCriterion("a_gender like", value, "aGender");
            return (Criteria) this;
        }

        public Criteria andAGenderNotLike(String value) {
            addCriterion("a_gender not like", value, "aGender");
            return (Criteria) this;
        }

        public Criteria andAGenderIn(List<String> values) {
            addCriterion("a_gender in", values, "aGender");
            return (Criteria) this;
        }

        public Criteria andAGenderNotIn(List<String> values) {
            addCriterion("a_gender not in", values, "aGender");
            return (Criteria) this;
        }

        public Criteria andAGenderBetween(String value1, String value2) {
            addCriterion("a_gender between", value1, value2, "aGender");
            return (Criteria) this;
        }

        public Criteria andAGenderNotBetween(String value1, String value2) {
            addCriterion("a_gender not between", value1, value2, "aGender");
            return (Criteria) this;
        }

        public Criteria andABrithdateIsNull() {
            addCriterion("a_brithdate is null");
            return (Criteria) this;
        }

        public Criteria andABrithdateIsNotNull() {
            addCriterion("a_brithdate is not null");
            return (Criteria) this;
        }

        public Criteria andABrithdateEqualTo(Date value) {
            addCriterionForJDBCDate("a_brithdate =", value, "aBrithdate");
            return (Criteria) this;
        }

        public Criteria andABrithdateNotEqualTo(Date value) {
            addCriterionForJDBCDate("a_brithdate <>", value, "aBrithdate");
            return (Criteria) this;
        }

        public Criteria andABrithdateGreaterThan(Date value) {
            addCriterionForJDBCDate("a_brithdate >", value, "aBrithdate");
            return (Criteria) this;
        }

        public Criteria andABrithdateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("a_brithdate >=", value, "aBrithdate");
            return (Criteria) this;
        }

        public Criteria andABrithdateLessThan(Date value) {
            addCriterionForJDBCDate("a_brithdate <", value, "aBrithdate");
            return (Criteria) this;
        }

        public Criteria andABrithdateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("a_brithdate <=", value, "aBrithdate");
            return (Criteria) this;
        }

        public Criteria andABrithdateIn(List<Date> values) {
            addCriterionForJDBCDate("a_brithdate in", values, "aBrithdate");
            return (Criteria) this;
        }

        public Criteria andABrithdateNotIn(List<Date> values) {
            addCriterionForJDBCDate("a_brithdate not in", values, "aBrithdate");
            return (Criteria) this;
        }

        public Criteria andABrithdateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("a_brithdate between", value1, value2, "aBrithdate");
            return (Criteria) this;
        }

        public Criteria andABrithdateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("a_brithdate not between", value1, value2, "aBrithdate");
            return (Criteria) this;
        }

        public Criteria andAPhoneIsNull() {
            addCriterion("a_phone is null");
            return (Criteria) this;
        }

        public Criteria andAPhoneIsNotNull() {
            addCriterion("a_phone is not null");
            return (Criteria) this;
        }

        public Criteria andAPhoneEqualTo(String value) {
            addCriterion("a_phone =", value, "aPhone");
            return (Criteria) this;
        }

        public Criteria andAPhoneNotEqualTo(String value) {
            addCriterion("a_phone <>", value, "aPhone");
            return (Criteria) this;
        }

        public Criteria andAPhoneGreaterThan(String value) {
            addCriterion("a_phone >", value, "aPhone");
            return (Criteria) this;
        }

        public Criteria andAPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("a_phone >=", value, "aPhone");
            return (Criteria) this;
        }

        public Criteria andAPhoneLessThan(String value) {
            addCriterion("a_phone <", value, "aPhone");
            return (Criteria) this;
        }

        public Criteria andAPhoneLessThanOrEqualTo(String value) {
            addCriterion("a_phone <=", value, "aPhone");
            return (Criteria) this;
        }

        public Criteria andAPhoneLike(String value) {
            addCriterion("a_phone like", value, "aPhone");
            return (Criteria) this;
        }

        public Criteria andAPhoneNotLike(String value) {
            addCriterion("a_phone not like", value, "aPhone");
            return (Criteria) this;
        }

        public Criteria andAPhoneIn(List<String> values) {
            addCriterion("a_phone in", values, "aPhone");
            return (Criteria) this;
        }

        public Criteria andAPhoneNotIn(List<String> values) {
            addCriterion("a_phone not in", values, "aPhone");
            return (Criteria) this;
        }

        public Criteria andAPhoneBetween(String value1, String value2) {
            addCriterion("a_phone between", value1, value2, "aPhone");
            return (Criteria) this;
        }

        public Criteria andAPhoneNotBetween(String value1, String value2) {
            addCriterion("a_phone not between", value1, value2, "aPhone");
            return (Criteria) this;
        }

        public Criteria andAWorkNameIsNull() {
            addCriterion("a_work_name is null");
            return (Criteria) this;
        }

        public Criteria andAWorkNameIsNotNull() {
            addCriterion("a_work_name is not null");
            return (Criteria) this;
        }

        public Criteria andAWorkNameEqualTo(String value) {
            addCriterion("a_work_name =", value, "aWorkName");
            return (Criteria) this;
        }

        public Criteria andAWorkNameNotEqualTo(String value) {
            addCriterion("a_work_name <>", value, "aWorkName");
            return (Criteria) this;
        }

        public Criteria andAWorkNameGreaterThan(String value) {
            addCriterion("a_work_name >", value, "aWorkName");
            return (Criteria) this;
        }

        public Criteria andAWorkNameGreaterThanOrEqualTo(String value) {
            addCriterion("a_work_name >=", value, "aWorkName");
            return (Criteria) this;
        }

        public Criteria andAWorkNameLessThan(String value) {
            addCriterion("a_work_name <", value, "aWorkName");
            return (Criteria) this;
        }

        public Criteria andAWorkNameLessThanOrEqualTo(String value) {
            addCriterion("a_work_name <=", value, "aWorkName");
            return (Criteria) this;
        }

        public Criteria andAWorkNameLike(String value) {
            addCriterion("a_work_name like", value, "aWorkName");
            return (Criteria) this;
        }

        public Criteria andAWorkNameNotLike(String value) {
            addCriterion("a_work_name not like", value, "aWorkName");
            return (Criteria) this;
        }

        public Criteria andAWorkNameIn(List<String> values) {
            addCriterion("a_work_name in", values, "aWorkName");
            return (Criteria) this;
        }

        public Criteria andAWorkNameNotIn(List<String> values) {
            addCriterion("a_work_name not in", values, "aWorkName");
            return (Criteria) this;
        }

        public Criteria andAWorkNameBetween(String value1, String value2) {
            addCriterion("a_work_name between", value1, value2, "aWorkName");
            return (Criteria) this;
        }

        public Criteria andAWorkNameNotBetween(String value1, String value2) {
            addCriterion("a_work_name not between", value1, value2, "aWorkName");
            return (Criteria) this;
        }

        public Criteria andAImgIsNull() {
            addCriterion("a_img is null");
            return (Criteria) this;
        }

        public Criteria andAImgIsNotNull() {
            addCriterion("a_img is not null");
            return (Criteria) this;
        }

        public Criteria andAImgEqualTo(String value) {
            addCriterion("a_img =", value, "aImg");
            return (Criteria) this;
        }

        public Criteria andAImgNotEqualTo(String value) {
            addCriterion("a_img <>", value, "aImg");
            return (Criteria) this;
        }

        public Criteria andAImgGreaterThan(String value) {
            addCriterion("a_img >", value, "aImg");
            return (Criteria) this;
        }

        public Criteria andAImgGreaterThanOrEqualTo(String value) {
            addCriterion("a_img >=", value, "aImg");
            return (Criteria) this;
        }

        public Criteria andAImgLessThan(String value) {
            addCriterion("a_img <", value, "aImg");
            return (Criteria) this;
        }

        public Criteria andAImgLessThanOrEqualTo(String value) {
            addCriterion("a_img <=", value, "aImg");
            return (Criteria) this;
        }

        public Criteria andAImgLike(String value) {
            addCriterion("a_img like", value, "aImg");
            return (Criteria) this;
        }

        public Criteria andAImgNotLike(String value) {
            addCriterion("a_img not like", value, "aImg");
            return (Criteria) this;
        }

        public Criteria andAImgIn(List<String> values) {
            addCriterion("a_img in", values, "aImg");
            return (Criteria) this;
        }

        public Criteria andAImgNotIn(List<String> values) {
            addCriterion("a_img not in", values, "aImg");
            return (Criteria) this;
        }

        public Criteria andAImgBetween(String value1, String value2) {
            addCriterion("a_img between", value1, value2, "aImg");
            return (Criteria) this;
        }

        public Criteria andAImgNotBetween(String value1, String value2) {
            addCriterion("a_img not between", value1, value2, "aImg");
            return (Criteria) this;
        }

        public Criteria andAGradeIsNull() {
            addCriterion("a_grade is null");
            return (Criteria) this;
        }

        public Criteria andAGradeIsNotNull() {
            addCriterion("a_grade is not null");
            return (Criteria) this;
        }

        public Criteria andAGradeEqualTo(Byte value) {
            addCriterion("a_grade =", value, "aGrade");
            return (Criteria) this;
        }

        public Criteria andAGradeNotEqualTo(Byte value) {
            addCriterion("a_grade <>", value, "aGrade");
            return (Criteria) this;
        }

        public Criteria andAGradeGreaterThan(Byte value) {
            addCriterion("a_grade >", value, "aGrade");
            return (Criteria) this;
        }

        public Criteria andAGradeGreaterThanOrEqualTo(Byte value) {
            addCriterion("a_grade >=", value, "aGrade");
            return (Criteria) this;
        }

        public Criteria andAGradeLessThan(Byte value) {
            addCriterion("a_grade <", value, "aGrade");
            return (Criteria) this;
        }

        public Criteria andAGradeLessThanOrEqualTo(Byte value) {
            addCriterion("a_grade <=", value, "aGrade");
            return (Criteria) this;
        }

        public Criteria andAGradeIn(List<Byte> values) {
            addCriterion("a_grade in", values, "aGrade");
            return (Criteria) this;
        }

        public Criteria andAGradeNotIn(List<Byte> values) {
            addCriterion("a_grade not in", values, "aGrade");
            return (Criteria) this;
        }

        public Criteria andAGradeBetween(Byte value1, Byte value2) {
            addCriterion("a_grade between", value1, value2, "aGrade");
            return (Criteria) this;
        }

        public Criteria andAGradeNotBetween(Byte value1, Byte value2) {
            addCriterion("a_grade not between", value1, value2, "aGrade");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table admin
     *
     * @mbggenerated do_not_delete_during_merge Wed Jun 26 08:33:50 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table admin
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}