package com.zlx.clinic.entity;

import java.util.Date;

public class Admin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.a_id
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    private Integer aId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.a_password
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    private String aPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.a_name
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    private String aName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.a_gender
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    private String aGender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.a_brithdate
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    private Date aBrithdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.a_phone
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    private String aPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.a_work_name
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    private String aWorkName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.a_img
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    private String aImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.a_grade
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    private Byte aGrade;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.a_id
     *
     * @return the value of admin.a_id
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public Integer getaId() {
        return aId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.a_id
     *
     * @param aId the value for admin.a_id
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public void setaId(Integer aId) {
        this.aId = aId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.a_password
     *
     * @return the value of admin.a_password
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public String getaPassword() {
        return aPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.a_password
     *
     * @param aPassword the value for admin.a_password
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public void setaPassword(String aPassword) {
        this.aPassword = aPassword == null ? null : aPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.a_name
     *
     * @return the value of admin.a_name
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public String getaName() {
        return aName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.a_name
     *
     * @param aName the value for admin.a_name
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public void setaName(String aName) {
        this.aName = aName == null ? null : aName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.a_gender
     *
     * @return the value of admin.a_gender
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public String getaGender() {
        return aGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.a_gender
     *
     * @param aGender the value for admin.a_gender
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public void setaGender(String aGender) {
        this.aGender = aGender == null ? null : aGender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.a_brithdate
     *
     * @return the value of admin.a_brithdate
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public Date getaBrithdate() {
        return aBrithdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.a_brithdate
     *
     * @param aBrithdate the value for admin.a_brithdate
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public void setaBrithdate(Date aBrithdate) {
        this.aBrithdate = aBrithdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.a_phone
     *
     * @return the value of admin.a_phone
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public String getaPhone() {
        return aPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.a_phone
     *
     * @param aPhone the value for admin.a_phone
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public void setaPhone(String aPhone) {
        this.aPhone = aPhone == null ? null : aPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.a_work_name
     *
     * @return the value of admin.a_work_name
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public String getaWorkName() {
        return aWorkName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.a_work_name
     *
     * @param aWorkName the value for admin.a_work_name
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public void setaWorkName(String aWorkName) {
        this.aWorkName = aWorkName == null ? null : aWorkName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.a_img
     *
     * @return the value of admin.a_img
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public String getaImg() {
        return aImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.a_img
     *
     * @param aImg the value for admin.a_img
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public void setaImg(String aImg) {
        this.aImg = aImg == null ? null : aImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.a_grade
     *
     * @return the value of admin.a_grade
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public Byte getaGrade() {
        return aGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.a_grade
     *
     * @param aGrade the value for admin.a_grade
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public void setaGrade(Byte aGrade) {
        this.aGrade = aGrade;
    }
}