package com.zlx.clinic.entity;

import java.util.Date;

public class Doctor {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.d_id
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    private Integer dId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.d_password
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    private String dPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.d_name
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    private String dName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.d_gender
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    private String dGender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.d_birthdate
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    private Date dBirthdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.d_phone
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    private String dPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.d_work_name
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    private String dWorkName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.d_range
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    private Byte dRange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.d_img
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    private String dImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.r_id
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    private Integer rId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.d_id
     *
     * @return the value of doctor.d_id
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public Integer getdId() {
        return dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.d_id
     *
     * @param dId the value for doctor.d_id
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public void setdId(Integer dId) {
        this.dId = dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.d_password
     *
     * @return the value of doctor.d_password
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public String getdPassword() {
        return dPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.d_password
     *
     * @param dPassword the value for doctor.d_password
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public void setdPassword(String dPassword) {
        this.dPassword = dPassword == null ? null : dPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.d_name
     *
     * @return the value of doctor.d_name
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public String getdName() {
        return dName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.d_name
     *
     * @param dName the value for doctor.d_name
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public void setdName(String dName) {
        this.dName = dName == null ? null : dName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.d_gender
     *
     * @return the value of doctor.d_gender
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public String getdGender() {
        return dGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.d_gender
     *
     * @param dGender the value for doctor.d_gender
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public void setdGender(String dGender) {
        this.dGender = dGender == null ? null : dGender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.d_birthdate
     *
     * @return the value of doctor.d_birthdate
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public Date getdBirthdate() {
        return dBirthdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.d_birthdate
     *
     * @param dBirthdate the value for doctor.d_birthdate
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public void setdBirthdate(Date dBirthdate) {
        this.dBirthdate = dBirthdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.d_phone
     *
     * @return the value of doctor.d_phone
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public String getdPhone() {
        return dPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.d_phone
     *
     * @param dPhone the value for doctor.d_phone
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public void setdPhone(String dPhone) {
        this.dPhone = dPhone == null ? null : dPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.d_work_name
     *
     * @return the value of doctor.d_work_name
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public String getdWorkName() {
        return dWorkName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.d_work_name
     *
     * @param dWorkName the value for doctor.d_work_name
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public void setdWorkName(String dWorkName) {
        this.dWorkName = dWorkName == null ? null : dWorkName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.d_range
     *
     * @return the value of doctor.d_range
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public Byte getdRange() {
        return dRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.d_range
     *
     * @param dRange the value for doctor.d_range
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public void setdRange(Byte dRange) {
        this.dRange = dRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.d_img
     *
     * @return the value of doctor.d_img
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public String getdImg() {
        return dImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.d_img
     *
     * @param dImg the value for doctor.d_img
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public void setdImg(String dImg) {
        this.dImg = dImg == null ? null : dImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.r_id
     *
     * @return the value of doctor.r_id
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public Integer getrId() {
        return rId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.r_id
     *
     * @param rId the value for doctor.r_id
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public void setrId(Integer rId) {
        this.rId = rId;
    }

    @Override
    public String toString() {
        return "Doctor{" +
                "dId=" + dId +
                ", dPassword='" + dPassword + '\'' +
                ", dName='" + dName + '\'' +
                ", dGender='" + dGender + '\'' +
                ", dBirthdate=" + dBirthdate +
                ", dPhone='" + dPhone + '\'' +
                ", dWorkName='" + dWorkName + '\'' +
                ", dRange=" + dRange +
                ", dImg='" + dImg + '\'' +
                ", rId=" + rId +
                '}';
    }
}