package com.zlx.clinic.entity;

import java.util.Date;

public class ItemOutTreate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_out_treate.i_id
     *
     * @mbggenerated Sun Jul 07 13:22:00 CST 2019
     */
    private Integer iId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_out_treate.d_id
     *
     * @mbggenerated Sun Jul 07 13:22:00 CST 2019
     */
    private Integer dId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_out_treate.d_count
     *
     * @mbggenerated Sun Jul 07 13:22:00 CST 2019
     */
    private Integer dCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_out_treate.d_all_count
     *
     * @mbggenerated Sun Jul 07 13:22:00 CST 2019
     */
    private Integer dAllCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_out_treate.o_id
     *
     * @mbggenerated Sun Jul 07 13:22:00 CST 2019
     */
    private Integer oId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_out_treate.i_date
     *
     * @mbggenerated Sun Jul 07 13:22:00 CST 2019
     */
    private Date iDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_out_treate.i_up_down
     *
     * @mbggenerated Sun Jul 07 13:22:00 CST 2019
     */
    private String iUpDown;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_out_treate.i_id
     *
     * @return the value of item_out_treate.i_id
     *
     * @mbggenerated Sun Jul 07 13:22:00 CST 2019
     */
    public Integer getiId() {
        return iId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_out_treate.i_id
     *
     * @param iId the value for item_out_treate.i_id
     *
     * @mbggenerated Sun Jul 07 13:22:00 CST 2019
     */
    public void setiId(Integer iId) {
        this.iId = iId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_out_treate.d_id
     *
     * @return the value of item_out_treate.d_id
     *
     * @mbggenerated Sun Jul 07 13:22:00 CST 2019
     */
    public Integer getdId() {
        return dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_out_treate.d_id
     *
     * @param dId the value for item_out_treate.d_id
     *
     * @mbggenerated Sun Jul 07 13:22:00 CST 2019
     */
    public void setdId(Integer dId) {
        this.dId = dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_out_treate.d_count
     *
     * @return the value of item_out_treate.d_count
     *
     * @mbggenerated Sun Jul 07 13:22:00 CST 2019
     */
    public Integer getdCount() {
        return dCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_out_treate.d_count
     *
     * @param dCount the value for item_out_treate.d_count
     *
     * @mbggenerated Sun Jul 07 13:22:00 CST 2019
     */
    public void setdCount(Integer dCount) {
        this.dCount = dCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_out_treate.d_all_count
     *
     * @return the value of item_out_treate.d_all_count
     *
     * @mbggenerated Sun Jul 07 13:22:00 CST 2019
     */
    public Integer getdAllCount() {
        return dAllCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_out_treate.d_all_count
     *
     * @param dAllCount the value for item_out_treate.d_all_count
     *
     * @mbggenerated Sun Jul 07 13:22:00 CST 2019
     */
    public void setdAllCount(Integer dAllCount) {
        this.dAllCount = dAllCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_out_treate.o_id
     *
     * @return the value of item_out_treate.o_id
     *
     * @mbggenerated Sun Jul 07 13:22:00 CST 2019
     */
    public Integer getoId() {
        return oId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_out_treate.o_id
     *
     * @param oId the value for item_out_treate.o_id
     *
     * @mbggenerated Sun Jul 07 13:22:00 CST 2019
     */
    public void setoId(Integer oId) {
        this.oId = oId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_out_treate.i_date
     *
     * @return the value of item_out_treate.i_date
     *
     * @mbggenerated Sun Jul 07 13:22:00 CST 2019
     */
    public Date getiDate() {
        return iDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_out_treate.i_date
     *
     * @param iDate the value for item_out_treate.i_date
     *
     * @mbggenerated Sun Jul 07 13:22:00 CST 2019
     */
    public void setiDate(Date iDate) {
        this.iDate = iDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_out_treate.i_up_down
     *
     * @return the value of item_out_treate.i_up_down
     *
     * @mbggenerated Sun Jul 07 13:22:00 CST 2019
     */
    public String getiUpDown() {
        return iUpDown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_out_treate.i_up_down
     *
     * @param iUpDown the value for item_out_treate.i_up_down
     *
     * @mbggenerated Sun Jul 07 13:22:00 CST 2019
     */
    public void setiUpDown(String iUpDown) {
        this.iUpDown = iUpDown == null ? null : iUpDown.trim();
    }
}