package com.zlx.clinic.entity;

import java.util.ArrayList;
import java.util.List;

public class MedicApplyExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table medic_apply
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table medic_apply
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table medic_apply
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medic_apply
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public MedicApplyExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medic_apply
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medic_apply
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medic_apply
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medic_apply
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medic_apply
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medic_apply
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medic_apply
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medic_apply
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medic_apply
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medic_apply
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table medic_apply
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMaIdIsNull() {
            addCriterion("ma_id is null");
            return (Criteria) this;
        }

        public Criteria andMaIdIsNotNull() {
            addCriterion("ma_id is not null");
            return (Criteria) this;
        }

        public Criteria andMaIdEqualTo(Integer value) {
            addCriterion("ma_id =", value, "maId");
            return (Criteria) this;
        }

        public Criteria andMaIdNotEqualTo(Integer value) {
            addCriterion("ma_id <>", value, "maId");
            return (Criteria) this;
        }

        public Criteria andMaIdGreaterThan(Integer value) {
            addCriterion("ma_id >", value, "maId");
            return (Criteria) this;
        }

        public Criteria andMaIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ma_id >=", value, "maId");
            return (Criteria) this;
        }

        public Criteria andMaIdLessThan(Integer value) {
            addCriterion("ma_id <", value, "maId");
            return (Criteria) this;
        }

        public Criteria andMaIdLessThanOrEqualTo(Integer value) {
            addCriterion("ma_id <=", value, "maId");
            return (Criteria) this;
        }

        public Criteria andMaIdIn(List<Integer> values) {
            addCriterion("ma_id in", values, "maId");
            return (Criteria) this;
        }

        public Criteria andMaIdNotIn(List<Integer> values) {
            addCriterion("ma_id not in", values, "maId");
            return (Criteria) this;
        }

        public Criteria andMaIdBetween(Integer value1, Integer value2) {
            addCriterion("ma_id between", value1, value2, "maId");
            return (Criteria) this;
        }

        public Criteria andMaIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ma_id not between", value1, value2, "maId");
            return (Criteria) this;
        }

        public Criteria andMIdIsNull() {
            addCriterion("m_id is null");
            return (Criteria) this;
        }

        public Criteria andMIdIsNotNull() {
            addCriterion("m_id is not null");
            return (Criteria) this;
        }

        public Criteria andMIdEqualTo(Integer value) {
            addCriterion("m_id =", value, "mId");
            return (Criteria) this;
        }

        public Criteria andMIdNotEqualTo(Integer value) {
            addCriterion("m_id <>", value, "mId");
            return (Criteria) this;
        }

        public Criteria andMIdGreaterThan(Integer value) {
            addCriterion("m_id >", value, "mId");
            return (Criteria) this;
        }

        public Criteria andMIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("m_id >=", value, "mId");
            return (Criteria) this;
        }

        public Criteria andMIdLessThan(Integer value) {
            addCriterion("m_id <", value, "mId");
            return (Criteria) this;
        }

        public Criteria andMIdLessThanOrEqualTo(Integer value) {
            addCriterion("m_id <=", value, "mId");
            return (Criteria) this;
        }

        public Criteria andMIdIn(List<Integer> values) {
            addCriterion("m_id in", values, "mId");
            return (Criteria) this;
        }

        public Criteria andMIdNotIn(List<Integer> values) {
            addCriterion("m_id not in", values, "mId");
            return (Criteria) this;
        }

        public Criteria andMIdBetween(Integer value1, Integer value2) {
            addCriterion("m_id between", value1, value2, "mId");
            return (Criteria) this;
        }

        public Criteria andMIdNotBetween(Integer value1, Integer value2) {
            addCriterion("m_id not between", value1, value2, "mId");
            return (Criteria) this;
        }

        public Criteria andMaCountIsNull() {
            addCriterion("ma_count is null");
            return (Criteria) this;
        }

        public Criteria andMaCountIsNotNull() {
            addCriterion("ma_count is not null");
            return (Criteria) this;
        }

        public Criteria andMaCountEqualTo(Integer value) {
            addCriterion("ma_count =", value, "maCount");
            return (Criteria) this;
        }

        public Criteria andMaCountNotEqualTo(Integer value) {
            addCriterion("ma_count <>", value, "maCount");
            return (Criteria) this;
        }

        public Criteria andMaCountGreaterThan(Integer value) {
            addCriterion("ma_count >", value, "maCount");
            return (Criteria) this;
        }

        public Criteria andMaCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("ma_count >=", value, "maCount");
            return (Criteria) this;
        }

        public Criteria andMaCountLessThan(Integer value) {
            addCriterion("ma_count <", value, "maCount");
            return (Criteria) this;
        }

        public Criteria andMaCountLessThanOrEqualTo(Integer value) {
            addCriterion("ma_count <=", value, "maCount");
            return (Criteria) this;
        }

        public Criteria andMaCountIn(List<Integer> values) {
            addCriterion("ma_count in", values, "maCount");
            return (Criteria) this;
        }

        public Criteria andMaCountNotIn(List<Integer> values) {
            addCriterion("ma_count not in", values, "maCount");
            return (Criteria) this;
        }

        public Criteria andMaCountBetween(Integer value1, Integer value2) {
            addCriterion("ma_count between", value1, value2, "maCount");
            return (Criteria) this;
        }

        public Criteria andMaCountNotBetween(Integer value1, Integer value2) {
            addCriterion("ma_count not between", value1, value2, "maCount");
            return (Criteria) this;
        }

        public Criteria andAIdIsNull() {
            addCriterion("a_id is null");
            return (Criteria) this;
        }

        public Criteria andAIdIsNotNull() {
            addCriterion("a_id is not null");
            return (Criteria) this;
        }

        public Criteria andAIdEqualTo(Integer value) {
            addCriterion("a_id =", value, "aId");
            return (Criteria) this;
        }

        public Criteria andAIdNotEqualTo(Integer value) {
            addCriterion("a_id <>", value, "aId");
            return (Criteria) this;
        }

        public Criteria andAIdGreaterThan(Integer value) {
            addCriterion("a_id >", value, "aId");
            return (Criteria) this;
        }

        public Criteria andAIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("a_id >=", value, "aId");
            return (Criteria) this;
        }

        public Criteria andAIdLessThan(Integer value) {
            addCriterion("a_id <", value, "aId");
            return (Criteria) this;
        }

        public Criteria andAIdLessThanOrEqualTo(Integer value) {
            addCriterion("a_id <=", value, "aId");
            return (Criteria) this;
        }

        public Criteria andAIdIn(List<Integer> values) {
            addCriterion("a_id in", values, "aId");
            return (Criteria) this;
        }

        public Criteria andAIdNotIn(List<Integer> values) {
            addCriterion("a_id not in", values, "aId");
            return (Criteria) this;
        }

        public Criteria andAIdBetween(Integer value1, Integer value2) {
            addCriterion("a_id between", value1, value2, "aId");
            return (Criteria) this;
        }

        public Criteria andAIdNotBetween(Integer value1, Integer value2) {
            addCriterion("a_id not between", value1, value2, "aId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table medic_apply
     *
     * @mbggenerated do_not_delete_during_merge Wed Jun 26 08:33:50 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table medic_apply
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}