package com.zlx.clinic.entity;

public class MedicOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medic_order.mo_id
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    private Integer moId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medic_order.m_id
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    private Integer mId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medic_order.m_count
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    private Integer mCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medic_order.t_id
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    private Integer tId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medic_order.mo_id
     *
     * @return the value of medic_order.mo_id
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public Integer getMoId() {
        return moId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medic_order.mo_id
     *
     * @param moId the value for medic_order.mo_id
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public void setMoId(Integer moId) {
        this.moId = moId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medic_order.m_id
     *
     * @return the value of medic_order.m_id
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public Integer getmId() {
        return mId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medic_order.m_id
     *
     * @param mId the value for medic_order.m_id
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public void setmId(Integer mId) {
        this.mId = mId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medic_order.m_count
     *
     * @return the value of medic_order.m_count
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public Integer getmCount() {
        return mCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medic_order.m_count
     *
     * @param mCount the value for medic_order.m_count
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public void setmCount(Integer mCount) {
        this.mCount = mCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medic_order.t_id
     *
     * @return the value of medic_order.t_id
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public Integer gettId() {
        return tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medic_order.t_id
     *
     * @param tId the value for medic_order.t_id
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public void settId(Integer tId) {
        this.tId = tId;
    }
}