package com.zlx.clinic.entity;

public class MedicApply {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medic_apply.ma_id
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    private Integer maId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medic_apply.m_id
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    private Integer mId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medic_apply.ma_count
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    private Integer maCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medic_apply.a_id
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    private Integer aId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medic_apply.ma_id
     *
     * @return the value of medic_apply.ma_id
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public Integer getMaId() {
        return maId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medic_apply.ma_id
     *
     * @param maId the value for medic_apply.ma_id
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public void setMaId(Integer maId) {
        this.maId = maId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medic_apply.m_id
     *
     * @return the value of medic_apply.m_id
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public Integer getmId() {
        return mId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medic_apply.m_id
     *
     * @param mId the value for medic_apply.m_id
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public void setmId(Integer mId) {
        this.mId = mId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medic_apply.ma_count
     *
     * @return the value of medic_apply.ma_count
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public Integer getMaCount() {
        return maCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medic_apply.ma_count
     *
     * @param maCount the value for medic_apply.ma_count
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public void setMaCount(Integer maCount) {
        this.maCount = maCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medic_apply.a_id
     *
     * @return the value of medic_apply.a_id
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public Integer getaId() {
        return aId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medic_apply.a_id
     *
     * @param aId the value for medic_apply.a_id
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public void setaId(Integer aId) {
        this.aId = aId;
    }
}