package com.zlx.clinic.entity;

import java.util.Date;

public class OutTreate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_treate.o_id
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    private Integer oId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_treate.r_id
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    private Integer rId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_treate.o_date
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    private Date oDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_treate.o_time
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    private String oTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_treate.o_id
     *
     * @return the value of out_treate.o_id
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public Integer getoId() {
        return oId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_treate.o_id
     *
     * @param oId the value for out_treate.o_id
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public void setoId(Integer oId) {
        this.oId = oId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_treate.r_id
     *
     * @return the value of out_treate.r_id
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public Integer getrId() {
        return rId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_treate.r_id
     *
     * @param rId the value for out_treate.r_id
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public void setrId(Integer rId) {
        this.rId = rId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_treate.o_date
     *
     * @return the value of out_treate.o_date
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public Date getoDate() {
        return oDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_treate.o_date
     *
     * @param oDate the value for out_treate.o_date
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public void setoDate(Date oDate) {
        this.oDate = oDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_treate.o_time
     *
     * @return the value of out_treate.o_time
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public String getoTime() {
        return oTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_treate.o_time
     *
     * @param oTime the value for out_treate.o_time
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public void setoTime(String oTime) {
        this.oTime = oTime == null ? null : oTime.trim();
    }
}