package com.zlx.clinic.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class PatientExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table patient
     *
     * @mbggenerated Tue Jul 09 15:54:34 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table patient
     *
     * @mbggenerated Tue Jul 09 15:54:34 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table patient
     *
     * @mbggenerated Tue Jul 09 15:54:34 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient
     *
     * @mbggenerated Tue Jul 09 15:54:34 CST 2019
     */
    public PatientExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient
     *
     * @mbggenerated Tue Jul 09 15:54:34 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient
     *
     * @mbggenerated Tue Jul 09 15:54:34 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient
     *
     * @mbggenerated Tue Jul 09 15:54:34 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient
     *
     * @mbggenerated Tue Jul 09 15:54:34 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient
     *
     * @mbggenerated Tue Jul 09 15:54:34 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient
     *
     * @mbggenerated Tue Jul 09 15:54:34 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient
     *
     * @mbggenerated Tue Jul 09 15:54:34 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient
     *
     * @mbggenerated Tue Jul 09 15:54:34 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient
     *
     * @mbggenerated Tue Jul 09 15:54:34 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient
     *
     * @mbggenerated Tue Jul 09 15:54:34 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table patient
     *
     * @mbggenerated Tue Jul 09 15:54:34 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andPIdIsNull() {
            addCriterion("p_id is null");
            return (Criteria) this;
        }

        public Criteria andPIdIsNotNull() {
            addCriterion("p_id is not null");
            return (Criteria) this;
        }

        public Criteria andPIdEqualTo(Integer value) {
            addCriterion("p_id =", value, "pId");
            return (Criteria) this;
        }

        public Criteria andPIdNotEqualTo(Integer value) {
            addCriterion("p_id <>", value, "pId");
            return (Criteria) this;
        }

        public Criteria andPIdGreaterThan(Integer value) {
            addCriterion("p_id >", value, "pId");
            return (Criteria) this;
        }

        public Criteria andPIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("p_id >=", value, "pId");
            return (Criteria) this;
        }

        public Criteria andPIdLessThan(Integer value) {
            addCriterion("p_id <", value, "pId");
            return (Criteria) this;
        }

        public Criteria andPIdLessThanOrEqualTo(Integer value) {
            addCriterion("p_id <=", value, "pId");
            return (Criteria) this;
        }

        public Criteria andPIdIn(List<Integer> values) {
            addCriterion("p_id in", values, "pId");
            return (Criteria) this;
        }

        public Criteria andPIdNotIn(List<Integer> values) {
            addCriterion("p_id not in", values, "pId");
            return (Criteria) this;
        }

        public Criteria andPIdBetween(Integer value1, Integer value2) {
            addCriterion("p_id between", value1, value2, "pId");
            return (Criteria) this;
        }

        public Criteria andPIdNotBetween(Integer value1, Integer value2) {
            addCriterion("p_id not between", value1, value2, "pId");
            return (Criteria) this;
        }

        public Criteria andPPasswordIsNull() {
            addCriterion("p_password is null");
            return (Criteria) this;
        }

        public Criteria andPPasswordIsNotNull() {
            addCriterion("p_password is not null");
            return (Criteria) this;
        }

        public Criteria andPPasswordEqualTo(String value) {
            addCriterion("p_password =", value, "pPassword");
            return (Criteria) this;
        }

        public Criteria andPPasswordNotEqualTo(String value) {
            addCriterion("p_password <>", value, "pPassword");
            return (Criteria) this;
        }

        public Criteria andPPasswordGreaterThan(String value) {
            addCriterion("p_password >", value, "pPassword");
            return (Criteria) this;
        }

        public Criteria andPPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("p_password >=", value, "pPassword");
            return (Criteria) this;
        }

        public Criteria andPPasswordLessThan(String value) {
            addCriterion("p_password <", value, "pPassword");
            return (Criteria) this;
        }

        public Criteria andPPasswordLessThanOrEqualTo(String value) {
            addCriterion("p_password <=", value, "pPassword");
            return (Criteria) this;
        }

        public Criteria andPPasswordLike(String value) {
            addCriterion("p_password like", value, "pPassword");
            return (Criteria) this;
        }

        public Criteria andPPasswordNotLike(String value) {
            addCriterion("p_password not like", value, "pPassword");
            return (Criteria) this;
        }

        public Criteria andPPasswordIn(List<String> values) {
            addCriterion("p_password in", values, "pPassword");
            return (Criteria) this;
        }

        public Criteria andPPasswordNotIn(List<String> values) {
            addCriterion("p_password not in", values, "pPassword");
            return (Criteria) this;
        }

        public Criteria andPPasswordBetween(String value1, String value2) {
            addCriterion("p_password between", value1, value2, "pPassword");
            return (Criteria) this;
        }

        public Criteria andPPasswordNotBetween(String value1, String value2) {
            addCriterion("p_password not between", value1, value2, "pPassword");
            return (Criteria) this;
        }

        public Criteria andPNameIsNull() {
            addCriterion("p_name is null");
            return (Criteria) this;
        }

        public Criteria andPNameIsNotNull() {
            addCriterion("p_name is not null");
            return (Criteria) this;
        }

        public Criteria andPNameEqualTo(String value) {
            addCriterion("p_name =", value, "pName");
            return (Criteria) this;
        }

        public Criteria andPNameNotEqualTo(String value) {
            addCriterion("p_name <>", value, "pName");
            return (Criteria) this;
        }

        public Criteria andPNameGreaterThan(String value) {
            addCriterion("p_name >", value, "pName");
            return (Criteria) this;
        }

        public Criteria andPNameGreaterThanOrEqualTo(String value) {
            addCriterion("p_name >=", value, "pName");
            return (Criteria) this;
        }

        public Criteria andPNameLessThan(String value) {
            addCriterion("p_name <", value, "pName");
            return (Criteria) this;
        }

        public Criteria andPNameLessThanOrEqualTo(String value) {
            addCriterion("p_name <=", value, "pName");
            return (Criteria) this;
        }

        public Criteria andPNameLike(String value) {
            addCriterion("p_name like", value, "pName");
            return (Criteria) this;
        }

        public Criteria andPNameNotLike(String value) {
            addCriterion("p_name not like", value, "pName");
            return (Criteria) this;
        }

        public Criteria andPNameIn(List<String> values) {
            addCriterion("p_name in", values, "pName");
            return (Criteria) this;
        }

        public Criteria andPNameNotIn(List<String> values) {
            addCriterion("p_name not in", values, "pName");
            return (Criteria) this;
        }

        public Criteria andPNameBetween(String value1, String value2) {
            addCriterion("p_name between", value1, value2, "pName");
            return (Criteria) this;
        }

        public Criteria andPNameNotBetween(String value1, String value2) {
            addCriterion("p_name not between", value1, value2, "pName");
            return (Criteria) this;
        }

        public Criteria andPGenderIsNull() {
            addCriterion("p_gender is null");
            return (Criteria) this;
        }

        public Criteria andPGenderIsNotNull() {
            addCriterion("p_gender is not null");
            return (Criteria) this;
        }

        public Criteria andPGenderEqualTo(String value) {
            addCriterion("p_gender =", value, "pGender");
            return (Criteria) this;
        }

        public Criteria andPGenderNotEqualTo(String value) {
            addCriterion("p_gender <>", value, "pGender");
            return (Criteria) this;
        }

        public Criteria andPGenderGreaterThan(String value) {
            addCriterion("p_gender >", value, "pGender");
            return (Criteria) this;
        }

        public Criteria andPGenderGreaterThanOrEqualTo(String value) {
            addCriterion("p_gender >=", value, "pGender");
            return (Criteria) this;
        }

        public Criteria andPGenderLessThan(String value) {
            addCriterion("p_gender <", value, "pGender");
            return (Criteria) this;
        }

        public Criteria andPGenderLessThanOrEqualTo(String value) {
            addCriterion("p_gender <=", value, "pGender");
            return (Criteria) this;
        }

        public Criteria andPGenderLike(String value) {
            addCriterion("p_gender like", value, "pGender");
            return (Criteria) this;
        }

        public Criteria andPGenderNotLike(String value) {
            addCriterion("p_gender not like", value, "pGender");
            return (Criteria) this;
        }

        public Criteria andPGenderIn(List<String> values) {
            addCriterion("p_gender in", values, "pGender");
            return (Criteria) this;
        }

        public Criteria andPGenderNotIn(List<String> values) {
            addCriterion("p_gender not in", values, "pGender");
            return (Criteria) this;
        }

        public Criteria andPGenderBetween(String value1, String value2) {
            addCriterion("p_gender between", value1, value2, "pGender");
            return (Criteria) this;
        }

        public Criteria andPGenderNotBetween(String value1, String value2) {
            addCriterion("p_gender not between", value1, value2, "pGender");
            return (Criteria) this;
        }

        public Criteria andPBirthdateIsNull() {
            addCriterion("p_birthdate is null");
            return (Criteria) this;
        }

        public Criteria andPBirthdateIsNotNull() {
            addCriterion("p_birthdate is not null");
            return (Criteria) this;
        }

        public Criteria andPBirthdateEqualTo(Date value) {
            addCriterionForJDBCDate("p_birthdate =", value, "pBirthdate");
            return (Criteria) this;
        }

        public Criteria andPBirthdateNotEqualTo(Date value) {
            addCriterionForJDBCDate("p_birthdate <>", value, "pBirthdate");
            return (Criteria) this;
        }

        public Criteria andPBirthdateGreaterThan(Date value) {
            addCriterionForJDBCDate("p_birthdate >", value, "pBirthdate");
            return (Criteria) this;
        }

        public Criteria andPBirthdateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("p_birthdate >=", value, "pBirthdate");
            return (Criteria) this;
        }

        public Criteria andPBirthdateLessThan(Date value) {
            addCriterionForJDBCDate("p_birthdate <", value, "pBirthdate");
            return (Criteria) this;
        }

        public Criteria andPBirthdateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("p_birthdate <=", value, "pBirthdate");
            return (Criteria) this;
        }

        public Criteria andPBirthdateIn(List<Date> values) {
            addCriterionForJDBCDate("p_birthdate in", values, "pBirthdate");
            return (Criteria) this;
        }

        public Criteria andPBirthdateNotIn(List<Date> values) {
            addCriterionForJDBCDate("p_birthdate not in", values, "pBirthdate");
            return (Criteria) this;
        }

        public Criteria andPBirthdateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("p_birthdate between", value1, value2, "pBirthdate");
            return (Criteria) this;
        }

        public Criteria andPBirthdateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("p_birthdate not between", value1, value2, "pBirthdate");
            return (Criteria) this;
        }

        public Criteria andPPhoneIsNull() {
            addCriterion("p_phone is null");
            return (Criteria) this;
        }

        public Criteria andPPhoneIsNotNull() {
            addCriterion("p_phone is not null");
            return (Criteria) this;
        }

        public Criteria andPPhoneEqualTo(String value) {
            addCriterion("p_phone =", value, "pPhone");
            return (Criteria) this;
        }

        public Criteria andPPhoneNotEqualTo(String value) {
            addCriterion("p_phone <>", value, "pPhone");
            return (Criteria) this;
        }

        public Criteria andPPhoneGreaterThan(String value) {
            addCriterion("p_phone >", value, "pPhone");
            return (Criteria) this;
        }

        public Criteria andPPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("p_phone >=", value, "pPhone");
            return (Criteria) this;
        }

        public Criteria andPPhoneLessThan(String value) {
            addCriterion("p_phone <", value, "pPhone");
            return (Criteria) this;
        }

        public Criteria andPPhoneLessThanOrEqualTo(String value) {
            addCriterion("p_phone <=", value, "pPhone");
            return (Criteria) this;
        }

        public Criteria andPPhoneLike(String value) {
            addCriterion("p_phone like", value, "pPhone");
            return (Criteria) this;
        }

        public Criteria andPPhoneNotLike(String value) {
            addCriterion("p_phone not like", value, "pPhone");
            return (Criteria) this;
        }

        public Criteria andPPhoneIn(List<String> values) {
            addCriterion("p_phone in", values, "pPhone");
            return (Criteria) this;
        }

        public Criteria andPPhoneNotIn(List<String> values) {
            addCriterion("p_phone not in", values, "pPhone");
            return (Criteria) this;
        }

        public Criteria andPPhoneBetween(String value1, String value2) {
            addCriterion("p_phone between", value1, value2, "pPhone");
            return (Criteria) this;
        }

        public Criteria andPPhoneNotBetween(String value1, String value2) {
            addCriterion("p_phone not between", value1, value2, "pPhone");
            return (Criteria) this;
        }

        public Criteria andPEmailIsNull() {
            addCriterion("p_email is null");
            return (Criteria) this;
        }

        public Criteria andPEmailIsNotNull() {
            addCriterion("p_email is not null");
            return (Criteria) this;
        }

        public Criteria andPEmailEqualTo(String value) {
            addCriterion("p_email =", value, "pEmail");
            return (Criteria) this;
        }

        public Criteria andPEmailNotEqualTo(String value) {
            addCriterion("p_email <>", value, "pEmail");
            return (Criteria) this;
        }

        public Criteria andPEmailGreaterThan(String value) {
            addCriterion("p_email >", value, "pEmail");
            return (Criteria) this;
        }

        public Criteria andPEmailGreaterThanOrEqualTo(String value) {
            addCriterion("p_email >=", value, "pEmail");
            return (Criteria) this;
        }

        public Criteria andPEmailLessThan(String value) {
            addCriterion("p_email <", value, "pEmail");
            return (Criteria) this;
        }

        public Criteria andPEmailLessThanOrEqualTo(String value) {
            addCriterion("p_email <=", value, "pEmail");
            return (Criteria) this;
        }

        public Criteria andPEmailLike(String value) {
            addCriterion("p_email like", value, "pEmail");
            return (Criteria) this;
        }

        public Criteria andPEmailNotLike(String value) {
            addCriterion("p_email not like", value, "pEmail");
            return (Criteria) this;
        }

        public Criteria andPEmailIn(List<String> values) {
            addCriterion("p_email in", values, "pEmail");
            return (Criteria) this;
        }

        public Criteria andPEmailNotIn(List<String> values) {
            addCriterion("p_email not in", values, "pEmail");
            return (Criteria) this;
        }

        public Criteria andPEmailBetween(String value1, String value2) {
            addCriterion("p_email between", value1, value2, "pEmail");
            return (Criteria) this;
        }

        public Criteria andPEmailNotBetween(String value1, String value2) {
            addCriterion("p_email not between", value1, value2, "pEmail");
            return (Criteria) this;
        }

        public Criteria andPIdcardIsNull() {
            addCriterion("p_idcard is null");
            return (Criteria) this;
        }

        public Criteria andPIdcardIsNotNull() {
            addCriterion("p_idcard is not null");
            return (Criteria) this;
        }

        public Criteria andPIdcardEqualTo(String value) {
            addCriterion("p_idcard =", value, "pIdcard");
            return (Criteria) this;
        }

        public Criteria andPIdcardNotEqualTo(String value) {
            addCriterion("p_idcard <>", value, "pIdcard");
            return (Criteria) this;
        }

        public Criteria andPIdcardGreaterThan(String value) {
            addCriterion("p_idcard >", value, "pIdcard");
            return (Criteria) this;
        }

        public Criteria andPIdcardGreaterThanOrEqualTo(String value) {
            addCriterion("p_idcard >=", value, "pIdcard");
            return (Criteria) this;
        }

        public Criteria andPIdcardLessThan(String value) {
            addCriterion("p_idcard <", value, "pIdcard");
            return (Criteria) this;
        }

        public Criteria andPIdcardLessThanOrEqualTo(String value) {
            addCriterion("p_idcard <=", value, "pIdcard");
            return (Criteria) this;
        }

        public Criteria andPIdcardLike(String value) {
            addCriterion("p_idcard like", value, "pIdcard");
            return (Criteria) this;
        }

        public Criteria andPIdcardNotLike(String value) {
            addCriterion("p_idcard not like", value, "pIdcard");
            return (Criteria) this;
        }

        public Criteria andPIdcardIn(List<String> values) {
            addCriterion("p_idcard in", values, "pIdcard");
            return (Criteria) this;
        }

        public Criteria andPIdcardNotIn(List<String> values) {
            addCriterion("p_idcard not in", values, "pIdcard");
            return (Criteria) this;
        }

        public Criteria andPIdcardBetween(String value1, String value2) {
            addCriterion("p_idcard between", value1, value2, "pIdcard");
            return (Criteria) this;
        }

        public Criteria andPIdcardNotBetween(String value1, String value2) {
            addCriterion("p_idcard not between", value1, value2, "pIdcard");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table patient
     *
     * @mbggenerated do_not_delete_during_merge Tue Jul 09 15:54:34 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table patient
     *
     * @mbggenerated Tue Jul 09 15:54:34 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}