package com.zlx.clinic.entity;

public class PatientOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_order.o_id
     *
     * @mbggenerated Wed Jun 26 11:02:05 CST 2019
     */
    private Integer oId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_order.p_id
     *
     * @mbggenerated Wed Jun 26 11:02:05 CST 2019
     */
    private Integer pId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_order.i_id
     *
     * @mbggenerated Wed Jun 26 11:02:05 CST 2019
     */
    private Integer iId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_order.o_id
     *
     * @return the value of patient_order.o_id
     *
     * @mbggenerated Wed Jun 26 11:02:05 CST 2019
     */
    public Integer getoId() {
        return oId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_order.o_id
     *
     * @param oId the value for patient_order.o_id
     *
     * @mbggenerated Wed Jun 26 11:02:05 CST 2019
     */
    public void setoId(Integer oId) {
        this.oId = oId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_order.p_id
     *
     * @return the value of patient_order.p_id
     *
     * @mbggenerated Wed Jun 26 11:02:05 CST 2019
     */
    public Integer getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_order.p_id
     *
     * @param pId the value for patient_order.p_id
     *
     * @mbggenerated Wed Jun 26 11:02:05 CST 2019
     */
    public void setpId(Integer pId) {
        this.pId = pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_order.i_id
     *
     * @return the value of patient_order.i_id
     *
     * @mbggenerated Wed Jun 26 11:02:05 CST 2019
     */
    public Integer getiId() {
        return iId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_order.i_id
     *
     * @param iId the value for patient_order.i_id
     *
     * @mbggenerated Wed Jun 26 11:02:05 CST 2019
     */
    public void setiId(Integer iId) {
        this.iId = iId;
    }
}