package com.zlx.clinic.entity;

import java.util.Date;

public class PatientOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_order.o_id
     *
     * @mbggenerated Tue Jul 02 19:50:23 CST 2019
     */
    private Integer oId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_order.p_id
     *
     * @mbggenerated Tue Jul 02 19:50:23 CST 2019
     */
    private Integer pId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_order.i_id
     *
     * @mbggenerated Tue Jul 02 19:50:23 CST 2019
     */
    private Integer iId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_order.o_go
     *
     * @mbggenerated Tue Jul 02 19:50:23 CST 2019
     */
    private Boolean oGo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_order.o_date
     *
     * @mbggenerated Tue Jul 02 19:50:23 CST 2019
     */
    private Date oDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_order.o_id
     *
     * @return the value of patient_order.o_id
     *
     * @mbggenerated Tue Jul 02 19:50:23 CST 2019
     */
    public Integer getoId() {
        return oId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_order.o_id
     *
     * @param oId the value for patient_order.o_id
     *
     * @mbggenerated Tue Jul 02 19:50:23 CST 2019
     */
    public void setoId(Integer oId) {
        this.oId = oId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_order.p_id
     *
     * @return the value of patient_order.p_id
     *
     * @mbggenerated Tue Jul 02 19:50:23 CST 2019
     */
    public Integer getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_order.p_id
     *
     * @param pId the value for patient_order.p_id
     *
     * @mbggenerated Tue Jul 02 19:50:23 CST 2019
     */
    public void setpId(Integer pId) {
        this.pId = pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_order.i_id
     *
     * @return the value of patient_order.i_id
     *
     * @mbggenerated Tue Jul 02 19:50:23 CST 2019
     */
    public Integer getiId() {
        return iId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_order.i_id
     *
     * @param iId the value for patient_order.i_id
     *
     * @mbggenerated Tue Jul 02 19:50:23 CST 2019
     */
    public void setiId(Integer iId) {
        this.iId = iId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_order.o_go
     *
     * @return the value of patient_order.o_go
     *
     * @mbggenerated Tue Jul 02 19:50:23 CST 2019
     */
    public Boolean getoGo() {
        return oGo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_order.o_go
     *
     * @param oGo the value for patient_order.o_go
     *
     * @mbggenerated Tue Jul 02 19:50:23 CST 2019
     */
    public void setoGo(Boolean oGo) {
        this.oGo = oGo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_order.o_date
     *
     * @return the value of patient_order.o_date
     *
     * @mbggenerated Tue Jul 02 19:50:23 CST 2019
     */
    public Date getoDate() {
        return oDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_order.o_date
     *
     * @param oDate the value for patient_order.o_date
     *
     * @mbggenerated Tue Jul 02 19:50:23 CST 2019
     */
    public void setoDate(Date oDate) {
        this.oDate = oDate;
    }
}