package com.zlx.clinic.entity;

import java.util.Date;

public class Patient {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.p_id
     *
     * @mbggenerated Tue Jul 09 15:54:34 CST 2019
     */
    private Integer pId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.p_password
     *
     * @mbggenerated Tue Jul 09 15:54:34 CST 2019
     */
    private String pPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.p_name
     *
     * @mbggenerated Tue Jul 09 15:54:34 CST 2019
     */
    private String pName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.p_gender
     *
     * @mbggenerated Tue Jul 09 15:54:34 CST 2019
     */
    private String pGender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.p_birthdate
     *
     * @mbggenerated Tue Jul 09 15:54:34 CST 2019
     */
    private Date pBirthdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.p_phone
     *
     * @mbggenerated Tue Jul 09 15:54:34 CST 2019
     */
    private String pPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.p_email
     *
     * @mbggenerated Tue Jul 09 15:54:34 CST 2019
     */
    private String pEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient.p_idcard
     *
     * @mbggenerated Tue Jul 09 15:54:34 CST 2019
     */
    private String pIdcard;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.p_id
     *
     * @return the value of patient.p_id
     *
     * @mbggenerated Tue Jul 09 15:54:34 CST 2019
     */
    public Integer getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.p_id
     *
     * @param pId the value for patient.p_id
     *
     * @mbggenerated Tue Jul 09 15:54:34 CST 2019
     */
    public void setpId(Integer pId) {
        this.pId = pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.p_password
     *
     * @return the value of patient.p_password
     *
     * @mbggenerated Tue Jul 09 15:54:34 CST 2019
     */
    public String getpPassword() {
        return pPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.p_password
     *
     * @param pPassword the value for patient.p_password
     *
     * @mbggenerated Tue Jul 09 15:54:34 CST 2019
     */
    public void setpPassword(String pPassword) {
        this.pPassword = pPassword == null ? null : pPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.p_name
     *
     * @return the value of patient.p_name
     *
     * @mbggenerated Tue Jul 09 15:54:34 CST 2019
     */
    public String getpName() {
        return pName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.p_name
     *
     * @param pName the value for patient.p_name
     *
     * @mbggenerated Tue Jul 09 15:54:34 CST 2019
     */
    public void setpName(String pName) {
        this.pName = pName == null ? null : pName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.p_gender
     *
     * @return the value of patient.p_gender
     *
     * @mbggenerated Tue Jul 09 15:54:34 CST 2019
     */
    public String getpGender() {
        return pGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.p_gender
     *
     * @param pGender the value for patient.p_gender
     *
     * @mbggenerated Tue Jul 09 15:54:34 CST 2019
     */
    public void setpGender(String pGender) {
        this.pGender = pGender == null ? null : pGender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.p_birthdate
     *
     * @return the value of patient.p_birthdate
     *
     * @mbggenerated Tue Jul 09 15:54:34 CST 2019
     */
    public Date getpBirthdate() {
        return pBirthdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.p_birthdate
     *
     * @param pBirthdate the value for patient.p_birthdate
     *
     * @mbggenerated Tue Jul 09 15:54:34 CST 2019
     */
    public void setpBirthdate(Date pBirthdate) {
        this.pBirthdate = pBirthdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.p_phone
     *
     * @return the value of patient.p_phone
     *
     * @mbggenerated Tue Jul 09 15:54:34 CST 2019
     */
    public String getpPhone() {
        return pPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.p_phone
     *
     * @param pPhone the value for patient.p_phone
     *
     * @mbggenerated Tue Jul 09 15:54:34 CST 2019
     */
    public void setpPhone(String pPhone) {
        this.pPhone = pPhone == null ? null : pPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.p_email
     *
     * @return the value of patient.p_email
     *
     * @mbggenerated Tue Jul 09 15:54:34 CST 2019
     */
    public String getpEmail() {
        return pEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.p_email
     *
     * @param pEmail the value for patient.p_email
     *
     * @mbggenerated Tue Jul 09 15:54:34 CST 2019
     */
    public void setpEmail(String pEmail) {
        this.pEmail = pEmail == null ? null : pEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient.p_idcard
     *
     * @return the value of patient.p_idcard
     *
     * @mbggenerated Tue Jul 09 15:54:34 CST 2019
     */
    public String getpIdcard() {
        return pIdcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient.p_idcard
     *
     * @param pIdcard the value for patient.p_idcard
     *
     * @mbggenerated Tue Jul 09 15:54:34 CST 2019
     */
    public void setpIdcard(String pIdcard) {
        this.pIdcard = pIdcard == null ? null : pIdcard.trim();
    }
}