package com.zlx.clinic.entity;

public class Room {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.r_id
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    private Integer rId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.r_name
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    private String rName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.a_id
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    private Integer aId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.d_id
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    private Integer dId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.r_id
     *
     * @return the value of room.r_id
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public Integer getrId() {
        return rId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.r_id
     *
     * @param rId the value for room.r_id
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public void setrId(Integer rId) {
        this.rId = rId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.r_name
     *
     * @return the value of room.r_name
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public String getrName() {
        return rName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.r_name
     *
     * @param rName the value for room.r_name
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public void setrName(String rName) {
        this.rName = rName == null ? null : rName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.a_id
     *
     * @return the value of room.a_id
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public Integer getaId() {
        return aId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.a_id
     *
     * @param aId the value for room.a_id
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public void setaId(Integer aId) {
        this.aId = aId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.d_id
     *
     * @return the value of room.d_id
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public Integer getdId() {
        return dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.d_id
     *
     * @param dId the value for room.d_id
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    public void setdId(Integer dId) {
        this.dId = dId;
    }
}