package com.zlx.clinic.mapper;

import com.zlx.clinic.entity.Medicine;
import com.zlx.clinic.entity.MedicineExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface MedicineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medicine
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    int countByExample(MedicineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medicine
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    int deleteByExample(MedicineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medicine
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    int deleteByPrimaryKey(Integer mId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medicine
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    int insert(Medicine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medicine
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    int insertSelective(Medicine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medicine
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    List<Medicine> selectByExample(MedicineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medicine
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    Medicine selectByPrimaryKey(Integer mId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medicine
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    int updateByExampleSelective(@Param("record") Medicine record, @Param("example") MedicineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medicine
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    int updateByExample(@Param("record") Medicine record, @Param("example") MedicineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medicine
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    int updateByPrimaryKeySelective(Medicine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medicine
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    int updateByPrimaryKey(Medicine record);
}