package com.zlx.clinic.mapper;

import com.zlx.clinic.entity.MedicOrder;
import com.zlx.clinic.entity.MedicOrderExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface MedicOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medic_order
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    int countByExample(MedicOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medic_order
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    int deleteByExample(MedicOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medic_order
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    int deleteByPrimaryKey(Integer moId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medic_order
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    int insert(MedicOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medic_order
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    int insertSelective(MedicOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medic_order
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    List<MedicOrder> selectByExample(MedicOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medic_order
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    MedicOrder selectByPrimaryKey(Integer moId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medic_order
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    int updateByExampleSelective(@Param("record") MedicOrder record, @Param("example") MedicOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medic_order
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    int updateByExample(@Param("record") MedicOrder record, @Param("example") MedicOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medic_order
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    int updateByPrimaryKeySelective(MedicOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medic_order
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    int updateByPrimaryKey(MedicOrder record);
}