package com.zlx.clinic.mapper;

import com.zlx.clinic.entity.OutTreate;
import com.zlx.clinic.entity.OutTreateExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface OutTreateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_treate
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    int countByExample(OutTreateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_treate
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    int deleteByExample(OutTreateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_treate
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    int deleteByPrimaryKey(Integer oId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_treate
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    int insert(OutTreate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_treate
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    int insertSelective(OutTreate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_treate
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    List<OutTreate> selectByExample(OutTreateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_treate
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    OutTreate selectByPrimaryKey(Integer oId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_treate
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    int updateByExampleSelective(@Param("record") OutTreate record, @Param("example") OutTreateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_treate
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    int updateByExample(@Param("record") OutTreate record, @Param("example") OutTreateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_treate
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    int updateByPrimaryKeySelective(OutTreate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_treate
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    int updateByPrimaryKey(OutTreate record);
}