package com.zlx.clinic.mapper;

import com.zlx.clinic.entity.PatientOrder;
import com.zlx.clinic.entity.PatientOrderExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PatientOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_order
     *
     * @mbggenerated Thu Jul 04 19:52:14 CST 2019
     */
    int countByExample(PatientOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_order
     *
     * @mbggenerated Thu Jul 04 19:52:14 CST 2019
     */
    int deleteByExample(PatientOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_order
     *
     * @mbggenerated Thu Jul 04 19:52:14 CST 2019
     */
    int deleteByPrimaryKey(Integer oId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_order
     *
     * @mbggenerated Thu Jul 04 19:52:14 CST 2019
     */
    int insert(PatientOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_order
     *
     * @mbggenerated Thu Jul 04 19:52:14 CST 2019
     */
    int insertSelective(PatientOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_order
     *
     * @mbggenerated Thu Jul 04 19:52:14 CST 2019
     */
    List<PatientOrder> selectByExample(PatientOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_order
     *
     * @mbggenerated Thu Jul 04 19:52:14 CST 2019
     */
    PatientOrder selectByPrimaryKey(Integer oId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_order
     *
     * @mbggenerated Thu Jul 04 19:52:14 CST 2019
     */
    int updateByExampleSelective(@Param("record") PatientOrder record, @Param("example") PatientOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_order
     *
     * @mbggenerated Thu Jul 04 19:52:14 CST 2019
     */
    int updateByExample(@Param("record") PatientOrder record, @Param("example") PatientOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_order
     *
     * @mbggenerated Thu Jul 04 19:52:14 CST 2019
     */
    int updateByPrimaryKeySelective(PatientOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_order
     *
     * @mbggenerated Thu Jul 04 19:52:14 CST 2019
     */
    int updateByPrimaryKey(PatientOrder record);
}