package com.zlx.clinic.mapper;

import com.zlx.clinic.entity.Patient;
import com.zlx.clinic.entity.PatientExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PatientMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient
     *
     * @mbggenerated Tue Jul 09 15:54:34 CST 2019
     */
    int countByExample(PatientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient
     *
     * @mbggenerated Tue Jul 09 15:54:34 CST 2019
     */
    int deleteByExample(PatientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient
     *
     * @mbggenerated Tue Jul 09 15:54:34 CST 2019
     */
    int deleteByPrimaryKey(Integer pId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient
     *
     * @mbggenerated Tue Jul 09 15:54:34 CST 2019
     */
    int insert(Patient record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient
     *
     * @mbggenerated Tue Jul 09 15:54:34 CST 2019
     */
    int insertSelective(Patient record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient
     *
     * @mbggenerated Tue Jul 09 15:54:34 CST 2019
     */
    List<Patient> selectByExample(PatientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient
     *
     * @mbggenerated Tue Jul 09 15:54:34 CST 2019
     */
    Patient selectByPrimaryKey(Integer pId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient
     *
     * @mbggenerated Tue Jul 09 15:54:34 CST 2019
     */
    int updateByExampleSelective(@Param("record") Patient record, @Param("example") PatientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient
     *
     * @mbggenerated Tue Jul 09 15:54:34 CST 2019
     */
    int updateByExample(@Param("record") Patient record, @Param("example") PatientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient
     *
     * @mbggenerated Tue Jul 09 15:54:34 CST 2019
     */
    int updateByPrimaryKeySelective(Patient record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient
     *
     * @mbggenerated Tue Jul 09 15:54:34 CST 2019
     */
    int updateByPrimaryKey(Patient record);
}