package com.zlx.clinic.mapper;

import com.zlx.clinic.entity.Treat;
import com.zlx.clinic.entity.TreatExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TreatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treat
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    int countByExample(TreatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treat
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    int deleteByExample(TreatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treat
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    int deleteByPrimaryKey(Integer tId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treat
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    int insert(Treat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treat
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    int insertSelective(Treat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treat
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    List<Treat> selectByExample(TreatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treat
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    Treat selectByPrimaryKey(Integer tId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treat
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    int updateByExampleSelective(@Param("record") Treat record, @Param("example") TreatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treat
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    int updateByExample(@Param("record") Treat record, @Param("example") TreatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treat
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    int updateByPrimaryKeySelective(Treat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table treat
     *
     * @mbggenerated Wed Jun 26 08:33:50 CST 2019
     */
    int updateByPrimaryKey(Treat record);
}